//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamista.BL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Persona
    {
        public int Id { get; set; }
       
        public Nullable<int> tipoDocumento { get; set; }
        [DisplayName ("Documento")]
        public string numDocumento { get; set; }
        [DisplayName("Fecha Nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> genero { get; set; }
        [DisplayName("Nombres")]
        public string nombres { get; set; }
        [DisplayName("Apellidos")]
        public string apellidos { get; set; }
        [DisplayName("Dirección")]
        public string direccion { get; set; }
        [DisplayName("Teléfono")]
        public string telefono { get; set; }
        public string observaciones { get; set; }
    }
}
