//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliaciones
    {
        public int Id { get; set; }
        public int PrestadorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EstadoId { get; set; }
        public byte EstRegistro { get; set; }
    
        public virtual Prestadores Prestadores { get; set; }
    }
}
