//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditos
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public int PrestadorId { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal Porcentaje { get; set; }
        public int PeriodoId { get; set; }
        public string Observacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TPeriodos TPeriodos { get; set; }
        public virtual Prestadores Prestadores { get; set; }
    }
}
