//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestamista
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdEntities : DbContext
    {
        public bdEntities()
            : base("name=bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliaciones> Afiliaciones { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Creditos> Creditos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Movimientos> Movimientos { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Prestadores> Prestadores { get; set; }
        public virtual DbSet<TDocumentos> TDocumentos { get; set; }
        public virtual DbSet<TEstados> TEstados { get; set; }
        public virtual DbSet<TGeneros> TGeneros { get; set; }
        public virtual DbSet<TPeriodos> TPeriodos { get; set; }
    }
}
